#!/bin/bash

proxyAddress="10.0.0.253"
proxyPort="8080"
localDomain=",.myDomain"
proxyUsername="myUserName"

function proxyUserLogin()
{
    # read -p "Enter your (Proxy) username: " proxyUsername
    # read -s -p "And now enter your password: " proxyPassword
    read -s -p "Please enter your (proxy) password: " proxyPassword
    echo
}

function proxy_on()
{
    buildProxyDic
    proxyUserLogin
    proxyBuildCommon
    unset proxyDic
}

function proxy_off()
{
    buildProxyDic
    for proxyType in "${proxyDic[@]}"
    do
        local upperType="$(echo $proxyType | tr '[a-z]' '[A-Z]')"

        unset $proxyType
        unset $upperType
    done
    unset no_proxy
    unset proxyDic

    echo -e "Proxy environment variable removed."
}

function buildProxyDic()
{
    proxyDic=(
        http_proxy
        ftp_proxy
        https_proxy
        rsync_proxy
        socks_proxy
    )
}

function proxyBuildCommon()
{
    export no_proxy="localhost,127.0.1.1,127.0.0.1/8,192.168.0.0/8,192.168.0.0/16,10.0.0.0/8,10.0.0.0/16"$localDomain
    local server=$proxyAddress
    local port=$proxyPort
    local proxyConf="http://$proxyUsername:$proxyPassword@$server:$port/"

    for proxyType in "${proxyDic[@]}"
    do
        local upperType="$(echo $proxyType | tr '[a-z]' '[A-Z]')"

        export $proxyType=$proxyConf
        export $upperType=$proxyConf
    done

    echo "    Proxy set for: "$proxyUsername
    echo

    unset proxyUsername
    unset proxyPassword
}
